### ISSUE TITLE
Back-end basic functionalities

### ISSUE THREAD

**Issue by hajicj** [ipsamiotis/mei_transcriber#10]
The back-end should have the following functionalities:

- [x] Accommodate a running MongoDB database
- [x] Converter module
    - [x] PDF -> JPEG
    - [x] Conversion evaluation
    - [x] Follow file naming conventions
    - [x] Store PDF, PNG, JPEG, MEI to file system
- [x] Store files in file system (following #8 conventions)

**Comment by ipsamiotis** [comment]
Broke down the issue to better tackle individual problems. Most goals of the issue were met so it closes.
