### ISSUE TITLE
Save MEI from editor to back-end

### ISSUE THREAD

**Issue by hajicj** [ipsamiotis/mei_transcriber#14]
- [x] Save button in the UI
- [x] Actually store the MEI to the back-end

Next time the page loads, it should load the MEI with the (partial) transcription
- [ ] ...check that this indeed works

**Comment by ipsamiotis** [comment]
This should store the MEI in a correct way, being compatible with #18

**Comment by ipsamiotis** [comment]
See issue #21 for a follow up to this issue.
