### ISSUE TITLE
MemoryError on PDF convertor

### ISSUE THREAD

**Issue by hajicj** [ipsamiotis/mei_transcriber#16]
When converting a PDF to a page list & images, sometimes a MemoryError happens. This can be solved by converting not the whole file, but by converting each page individually.

**Comment by ipsamiotis** [comment]
### IMPORTANT

We need specifics on **how to replicate the bug**. I couldn't replicate it in the current state of _dev_, so we need to all test it to see what causes it.

**Comment by ipsamiotis** [comment]
This issue is resolved by the functionality of the external backend.
