### ISSUE TITLE
Building Back-end Database

### ISSUE THREAD

**Issue by hajicj** [ipsamiotis/mei_transcriber#8]
We need a database solution to store music composition data.

- [x] Use MongoDB to store data for an initial solution.
- [ ] Store files in directories. Organizational consensus: 
    * composer_name/composition_name/instrument/data_modality/file_uid/file
    * Ludwig_van_Beethoven/Andante_F_Major/piano/pdf/30912749289/page1.pdf
- [x] Store directories and metadata per composition in MongoDB
    * Look wiki for current schema

**Comment by ipsamiotis** [comment]
### IMPORTANT

The directories right now are not generated correctly based on consensus. This needs to be fixed to close the issue for the Feature.

**Comment by ipsamiotis** [comment]
Considering the current state of the backend, the current functionality is sufficient for this issue.
